/**
 * Post-build step for the Workers deployment.
 *
 * Writes `build/.assetsignore` so `wrangler deploy` skips files that only exist
 * for local debugging. Sourcemaps alone are ~70 MB of the build output and are
 * never fetched by the browser unless devtools is open.
 */

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const buildDir = join(dirname(fileURLToPath(import.meta.url)), '..', '..', 'build');

writeFileSync(
	join(buildDir, '.assetsignore'),
	['# Generated by workers/scripts/postbuild.mjs', '*.map', '**/*.map', ''].join('\n')
);

console.log('build/.assetsignore written (sourcemaps excluded from the Workers upload)');
